language: java

jdk:
  - openjdk14

services:
  - postgresql

before_install:
  - psql -c 'create database grabber;' -U postgres

sudo: false

env:
  global:
    - CODECOV_TOKEN="8c730528-d6ed-4361-9941-703205a72c4c"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -s_manannikov@mail.ru
    on_success: never # default: change
    on_failure: always # default: always